### PR TITLE
Fixing the issues preventing this plugin from working with 0.7.x 

### LINKED ISSUE #6: my own answer to poll was not included until after refreshing the page
* Poll plugin displays the choices and when user makes a selection it switches to the results view
* User expects to see result including their own vote but that view does not include the current vote by user. This will be specially noticeable initially when there is zero or very few votes.
* Once user refreshes the view, the poll updates to show current data

It looks like this is just a matter of pulling latest poll data before displaying the results view

### PR DESCRIPTION
**Pull request by zetas**
I'm not a nodebb plugin dev, I basically went through the code looking for mismatched html anchors and fixed them. It's entirely possible these changes only work with the Persona theme for 0.7.x, not sure how different they are as far as markup is concerned. 

Here's the list of changes:

* Fix #6 so your choice, as well as vote count/percentage is shown after you vote
* Fixes issue #24, poll not being displayed at all due to bad markup identifiers
* Forces the poll creation window to sit above the compose panel instead of behind
* Fixes template parse error in poll/notify.tpl. The curly braces were somehow being translated into htmlcharcodes and it was breaking the JS. I couldn't figure out how to escape it so I refactored the function to accept the raw ID instead of an object.
* Added missing en_US translation (copied from en_GB). This seems to be a common issue, no plugin dev seems to prepare for the admin using en_US. I guess I'm the only one that doesn't leave it on GB haha.

@Schamper If you give me instructions as to what I may have done wrong or how I could do it better to fit with all themes, let me know and I'll add more to the PR.

### CODE REVIEW

File: public/js/poll/creator.js [hunk 1]
```diff
@@ -38,6 +38,7 @@
 				bootbox.dialog({
 					title: 'Create a poll',
 					message: html,
+					className: 'poll-creator',
```
Comment (zetas) [inline public/js/poll/creator.js]: Added class to bring poll creator window in front of the topic composer.

File: public/js/poll/main.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 (function() {
 	window.Poll = {
-		load: function(data) {
-			Poll.sockets.emit.load(data.pollid, function(err, poll) {
+		load: function(pollid) {
```
Comment (zetas) [inline public/js/poll/main.js]: Didn't see any reason to maintain the object parameter since only the pollid was being used.

File: public/js/poll/view.js [hunk 3]
```diff
@@ -63,7 +63,7 @@
 		},
 		insertPoll: function(poll, callback) {
 			View.parsePoll(poll, function(html) {
-				$('#post-container .post-row[data-index="0"] .post-content').prepend(html);
+				$('.clearfix[data-index="0"] .content').append(html);
```
Comment (zetas) [inline public/js/poll/view.js]: This is where I'm worried about it only supporting the Persona theme. Putting an anchor on all ```.clearfix``` tags seems shady but I couldn't find those id's anywhere (```#post-container``` & ```.post-row```)

File: public/js/poll/view.js [hunk 4]
```diff
@@ -86,9 +86,11 @@
 			poll = View.parseResults(poll);
 			for (var i = 0, l = poll.options.length; i < l; i++) {
 				var option = poll.options[i],
-					optionView = pollView.find('#pollResult' + option.id);
+				    optionView = pollView.find('.poll-view-result[data-poll-result="'+option.id+'"]');
```
Comment (zetas) [inline public/js/poll/view.js]: This I think is simply a 0.7.x compatibility issue but again the anchor was incorrect, ```#pollResult``` was nowhere to be found.

File: public/js/poll/view.js [hunk 5]
```diff
@@ -86,9 +86,11 @@
...
 				optionView.find('.poll-view-result-percentage').text(option.percentage + '%');
 				optionView.find('.poll-view-result-progressbar').css('width', option.percentage + '%');
+                		optionView.find('.poll-view-result-votecount').text(option.votecount + ' votes');
+
```
Comment (zetas) [inline public/js/poll/view.js]: For some reason this wasn't even being updated at all. The others weren't updated because the ```optionView``` wasn't being set right above but vote count never got any love...

File: public/less/style.less [hunk 6]
```diff
@@ -7,4 +7,8 @@
 
 .poll-view-result-avatar {
   width: 50px;
+}
+
+.poll-creator {
+  z-index: 11000 !important;
```
Comment (zetas) [inline public/less/style.less]: Like I said above this is to pop the creator over the topic composer instead of behind. I think the poll creator is always opened from the topic composer so it makes sense it should float above. The topic composer has a ```z-index``` of 10000 so had to go a bit higher and set the ```!important``` flag so it overwrites the default bootstrap modal ```z-index``` of 1080.

File: templates/poll/notify.tpl [hunk 7]
```diff
@@ -1 +1 @@
-<script>Poll.load({ pollid: {pollid} })</script>
```
Comment (zetas) [inline templates/poll/notify.tpl]: These outside curly braces were being converted to `&#123;` and `&#125` which are the html character codes for the curly braces. I tried escaping them with forward and back slash and everything else i could think of. I eventually settled on refactoring.

File: public/js/poll/view.js (hunk 3 above)
Comment (Schamper) [inline public/js/poll/view.js]: This might be a tricky one, those id's are probably very old and no longer used.

File: public/less/style.less (hunk 6 above)
Comment (Schamper) [inline public/less/style.less]: > The topic composer has a z-index of 10000

This didn't use to be an issue, but I suppose psychobunny decided on an insane z-index for the new composer :smile:

File: public/js/poll/view.js (hunk 4 above)
Comment (Schamper) [inline public/js/poll/view.js]: Looked like I forgot to change that when doing this: https://github.com/schamper/nodebb-plugin-poll/commit/b4a46561aff279e19c23b7c635fda5037c534b84

File: public/js/poll/main.js (hunk 2 above)
Comment (Schamper) [inline public/js/poll/main.js]: :+1:

**Comment by Schamper** [comment]
Looks all good except for the `.clearfix` "hack". Like I said in my comment there, I'd have to check some themes to see if there's a similarity. Or if you get the chance to do that before me, feel free to suggest something.

**Comment by zetas** [comment]
I'll spin up a dev install of 0.7.x and test multiple themes. I didn't want to spend too much time on it until I got a response from the maintainer :stuck_out_tongue:
